import { PhoneticItem } from "./phonetic/components/list";

export const phoneticData: PhoneticItem[] = [
  {
    dj: "iː",
    kk: "i",
    short: "如 'see' 中的 'ee'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ɪ",
    kk: "ɪ",
    short: "如 'sit' 中的 'i'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "e",
    kk: "e",
    short: "如 'say' 中的 'e'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "æ",
    kk: "æ",
    short: "如 'cat' 中的 'a'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ɑː",
    kk: "ɑ",
    short: "如 'father' 中的 'a'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ʌ",
    kk: "ʌ",
    short: "如 'cup' 中的 'u'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ɔː",
    kk: "ɔ",
    short: "如 'thought' 中的 'o'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "əʊ",
    kk: "o",
    short: "如 'go' 中的 'o'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "uː",
    kk: "u",
    short: "如 'too' 中的 'oo'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ʊ",
    kk: "ʊ",
    short: "如 'book' 中的 'oo'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ə",
    kk: "ə",
    short: "如 'sofa' 中的 'a'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ɜː",
    kk: "ɝ",
    short: "如 'bird' 中的 'ir'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "p",
    kk: "p",
    short: "如 'pat' 中的 'p'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "b",
    kk: "b",
    short: "如 'bat' 中的 'b'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "t",
    kk: "t",
    short: "如 'top' 中的 't'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "d",
    kk: "d",
    short: "如 'dog' 中的 'd'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "k",
    kk: "k",
    short: "如 'cat' 中的 'c'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "ɡ",
    kk: "ɡ",
    short: "如 'go' 中的 'g'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "f",
    kk: "f",
    short: "如 'fat' 中的 'f'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "v",
    kk: "v",
    short: "如 'vat' 中的 'v'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "θ",
    kk: "θ",
    short: "如 'thin' 中的 'th'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "ð",
    kk: "ð",
    short: "如 'this' 中的 'th'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "s",
    kk: "s",
    short: "如 'see' 中的 's'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "z",
    kk: "z",
    short: "如 'zoo' 中的 'z'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "ʃ",
    kk: "ʃ",
    short: "如 'she' 中的 'sh'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "ʒ",
    kk: "ʒ",
    short: "如 'measure' 中的 's'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "h",
    kk: "h",
    short: "如 'hat' 中的 'h'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "m",
    kk: "m",
    short: "如 'mat' 中的 'm'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "n",
    kk: "n",
    short: "如 'nap' 中的 'n'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "ŋ",
    kk: "ŋ",
    short: "如 'sing' 中的 'ng'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "l",
    kk: "l",
    short: "如 'lap' 中的 'l'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "r",
    kk: "r",
    short: "如 'rat' 中的 'r'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "j",
    kk: "j",
    short: "如 'yes' 中的 'y'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "w",
    kk: "w",
    short: "如 'wet' 中的 'w'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "tʃ",
    kk: "tʃ",
    short: "如 'chop' 中的 'ch'",
    isVowel: false,
    isVoiceless: true,
  },
  {
    dj: "dʒ",
    kk: "dʒ",
    short: "如 'jump' 中的 'j'",
    isVowel: false,
    isVoiceless: false,
  },
  {
    dj: "aɪ",
    kk: "aɪ",
    short: "如 'my' 中的 'y'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "aʊ",
    kk: "aʊ",
    short: "如 'now' 中的 'ow'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ɔɪ",
    kk: "ɔɪ",
    short: "如 'boy' 中的 'oy'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "eɪ",
    kk: "eɪ",
    short: "如 'say' 中的 'ay'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "əʊ",
    kk: "oʊ",
    short: "如 'go' 中的 'o'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ɪə",
    kk: "ɪr",
    short: "如 'near' 中的 'ear'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "eə",
    kk: "ɛr",
    short: "如 'hair' 中的 'air'",
    isVowel: true,
    isVoiceless: false,
  },
  {
    dj: "ʊə",
    kk: "ʊr",
    short: "如 'cure' 中的 'ure'",
    isVowel: true,
    isVoiceless: false,
  },
];
